import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { BlogProvider } from '@/context/BlogContext';


const roboto = Roboto({ 
  subsets: ["latin"],
  weight: ['400', '500', '700'], // Specify the weights you want to use
  style: ['normal', 'italic'] // Specify styles (optional)
});

export const metadata: Metadata = {
  title: "Proton Datalabs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <BlogProvider>
        {children}
        </BlogProvider>
      </body>
    </html>
  );
}
